
exts: [jpg, jpeg, png, webp, bmp]
recursive: true
sources:
  - name: real_ff
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/FaceForensics++/original_sequences
    label: 0
    dataset: ff
    domain: photo
    generator: real
    split_hint: seen

  - name: real_cdf
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/Celeb-DF-v2
    label: 0
    dataset: cdf
    domain: photo
    generator: real
    split_hint: seen

    # ================= 假图 (Fake) - 训练可见 (Seen) =================
  - name: fake_ddim
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/ddim
    label: 1
    dataset: df40
    domain: photo
    generator: ddim
    split_hint: seen

  - name: fake_dit
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/DiT
    label: 1
    dataset: df40
    domain: photo
    generator: dit
    split_hint: seen


  - name: fake_sd2.1
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/sd2.1
    label: 1
    dataset: df40
    domain: photo
    generator: sd2.1
    split_hint: seen

  - name: fake_stylegan3
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/StyleGAN3
    label: 1
    dataset: df40
    domain: photo
    generator: stylegan3
    split_hint: seen

  - name: fake_pixart
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/pixart
    label: 1
    dataset: df40
    domain: photo
    generator: pixart
    split_hint: seen

  - name: fake_rddm
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/RDDM
    label: 1
    dataset: df40
    domain: photo
    generator: rddm
    split_hint: seen

  - name: fake_styleganxl
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/StyleGANXL
    label: 1
    dataset: df40
    domain: photo
    generator: styleganxl
    split_hint: seen
    
    # ================= 假图 (Fake) - 仅测试可见 (Unseen Holdouts) =================
    # 将 SiT (现代扩散模型) 和 simswap (换脸) 留作泛化能力测试
  - name: fake_sit
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/SiT
    label: 1
    dataset: df40
    domain: photo
    generator: sit
    split_hint: unseen

  - name: fake_simswap
    path: /ai_paas_jf/ai_paas_weilx/datasets/DF40/DF40_train/simswap
    label: 1
    dataset: df40
    domain: photo
    generator: simswap
    split_hint: unseen

